-- Disease knowledge base seed data aligned with 2025 crop disease list
DELETE FROM disease_knowledge_data
WHERE crop_name IN ('Rice', 'Corn', 'Tomato', 'Strawberry', 'Citrus');

INSERT INTO disease_knowledge_data (
    disease_code,
    disease_name,
    crop_id,
    crop_name,
    description,
    symptom_summary,
    pathogen_type,
    risk_level,
    climate_risk_factors,
    created_at,
    updated_at
) VALUES
    -- Rice
    ('RICE_RICE_BLAST', '稻瘟病', 1, 'Rice',
     '稻瘟病由真菌引起，侵染叶、节、穗等多部位，易在高湿环境暴发。',
     '叶片出现梭形灰白斑，外围褐色，严重时造成枯死。',
     'Fungus', 'High', '连阴雨、高湿、昼夜温差大', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RICE_SHEATH_BLIGHT', '纹枯病', 1, 'Rice',
     '纹枯病由立枯丝核菌侵染，引起株丛枯萎，影响灌浆。',
     '叶鞘出现椭圆形浅褐斑，病斑逐步扩展并产生菌核。',
     'Fungus', 'Medium', '30℃左右高温及高湿环境', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RICE_BACTERIAL_BLIGHT', '白叶枯病', 1, 'Rice',
     '白叶枯病是由细菌侵染叶片导致的急性病害，传播迅速。',
     '叶片从叶尖起水渍状褪绿，后变黄白色并干枯。',
     'Bacteria', 'High', '风雨频繁、伤口多的田块', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    -- Corn / Maize
    ('CORN_LARGE_SPOT', '大斑病', 2, 'Corn',
     '大斑病由真菌侵染，叶片出现大型枯斑，影响光合效率。',
     '叶面出现梭形褐斑，中心灰色，边缘深色，严重时整个叶片枯死。',
     'Fungus', 'Medium', '高湿、多露的栽培环境', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CORN_VIRAL_DISEASE', '病毒病', 2, 'Corn',
     '玉米病毒病由多种病毒引起，造成植株矮缩和叶片花叶。',
     '叶片出现黄绿相间条斑或镶嵌状花叶，植株生长受阻。',
     'Virus', 'High', '蚜虫传毒、温暖潮湿', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CORN_RUST', '锈病', 2, 'Corn',
     '锈病为真菌性病害，叶片形成大量锈色孢子堆。',
     '叶片产生褐色粉状孢子堆，后期叶片早枯。',
     'Fungus', 'Medium', '昼夜温差大、空气湿度高', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CORN_SMALL_SPOT', '小斑病', 2, 'Corn',
     '小斑病主要危害叶片，形成细小褐色斑点，影响产量。',
     '叶片布满针尖大小褐色病斑，扩展后连成片状坏死。',
     'Fungus', 'Medium', '雨水频繁、密植田块', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    -- Tomato
    ('TOMATO_LATE_BLIGHT', '晚疫病', 4, 'Tomato',
     '晚疫病由致病疫霉侵染，极易在低温高湿条件下暴发。',
     '叶片先出现水渍状暗绿色斑，后变褐并产生白霉，果实腐烂。',
     'Fungus', 'High', '低温高湿、连续阴雨', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('TOMATO_GRAY_MOLD', '灰霉病', 4, 'Tomato',
     '灰霉病由灰葡萄孢引起，花、叶、果均可受害。',
     '病部覆有灰色霉层，组织腐烂并伴随灰色粉末状孢子。',
     'Fungus', 'High', '通风不良、湿度大于85%', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('TOMATO_DOWNY_MILDEW', '霜霉病', 4, 'Tomato',
     '霜霉病是低温高湿条件下多发的卵菌性病害。',
     '叶面现淡黄色斑块，背面生灰白色霉层，严重时叶片枯萎。',
     'Fungus', 'Medium', '低温高湿、凌晨露水重', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('TOMATO_EARLY_BLIGHT', '早疫病', 4, 'Tomato',
     '早疫病由交链孢菌侵染，叶片产生同心轮纹斑。',
     '叶片、茎秆与果实上形成褐色同心轮纹病斑，早期落叶严重。',
     'Fungus', 'Medium', '高温干湿交替、肥力偏低', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('TOMATO_LEAF_MINER', '潜叶蛾', 4, 'Tomato',
     '潜叶蛾幼虫潜食叶片，形成曲折虫道，严重影响光合作用。',
     '叶片产生银白色弯曲虫道，严重时叶片枯黄脱落。',
     'Insect', 'Medium', '干燥炎热、寄主密集', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('TOMATO_APHIDS', '蚜虫', 4, 'Tomato',
     '蚜虫刺吸汁液并传播病毒，造成植株萎缩卷叶。',
     '新梢和叶背聚集小型软体虫，叶片卷曲并伴随黏露。',
     'Insect', 'Medium', '温暖干燥、氮肥偏多', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('TOMATO_LEAF_MOLD', '叶霉病', 4, 'Tomato',
     '叶霉病在设施条件下高发，主要危害叶片。',
     '叶面出现黄色不规则斑，背面生橄榄绿色霉层，叶片早衰。',
     'Fungus', 'Medium', '湿度大于85%、通风不良', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('TOMATO_BACTERIAL_SPECK', '细菌性斑疹病', 4, 'Tomato',
     '细菌性斑疹病引起叶片小黑斑并扩展至果面。',
     '叶、果表面出现针尖大小黑褐斑，周围黄绿晕圈。',
     'Bacteria', 'Medium', '雨水频繁、温凉多湿', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('TOMATO_CANKER', '溃疡病', 4, 'Tomato',
     '番茄溃疡病由细菌感染，导致维管束褐变和茎部开裂。',
     '叶片边缘焦枯、茎部出现条状裂缝，果实生鸟眼状斑。',
     'Bacteria', 'High', '长时间高湿、土传带菌', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    -- Strawberry
    ('STRAWBERRY_ANGULAR_LEAF_SPOT', '角斑病', 5, 'Strawberry',
     '角斑病是由细菌侵染造成，叶片出现水渍状角形病斑。',
     '叶面油渍状小斑，沿叶脉扩展成角状半透明区域。',
     'Bacteria', 'Medium', '低温高湿、雨水飞溅', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('STRAWBERRY_POWDERY_MILDEW', '白粉病', 5, 'Strawberry',
     '白粉病为真菌性病害，叶片正反两面均可长出白粉。',
     '叶片卷曲并覆盖白色粉末状菌丝，果实表面粗糙。',
     'Fungus', 'Medium', '温差大、通风差', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('STRAWBERRY_GRAY_MOLD', '灰霉病', 5, 'Strawberry',
     '灰霉病主要危害花和果，导致果实腐烂并覆盖灰霉层。',
     '果实出现褐斑并迅速腐烂，表面布满灰褐色霉层。',
     'Fungus', 'High', '低温高湿、花期雨雾天', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('STRAWBERRY_ANTHRACNOSE_FRUIT_ROT', '炭疽果腐病', 5, 'Strawberry',
     '炭疽病侵染果实，引起硬化腐烂，对产量影响极大。',
     '果实出现凹陷黑褐斑，后期变硬并产生橙色黏质孢子。',
     'Fungus', 'High', '高温高湿、雨后连晴', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('STRAWBERRY_BLOSSOM_BLIGHT', '花枯病', 5, 'Strawberry',
     '花枯病导致花器褐变干枯，影响坐果。',
     '花瓣褐变、花托腐烂，幼果脱落，植株生长受阻。',
     'Fungus', 'Medium', '雨雾连绵、花期低温', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('STRAWBERRY_LEAF_SPOT', '叶斑病', 5, 'Strawberry',
     '叶斑病导致叶片出现紫褐色斑，严重时落叶。',
     '叶片布满紫褐色圆形病斑，中部灰白，边缘红褐。',
     'Fungus', 'Medium', '高湿度、植株郁闭', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('STRAWBERRY_BLACK_ROOT_ROT', '黑根腐病', 5, 'Strawberry',
     '黑根腐病侵染根系，造成植株衰弱死亡。',
     '根系变黑腐烂，植株萎蔫，果实瘦小品质差。',
     'Fungus', 'High', '排水不良、重茬连作', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    -- Citrus
    ('CITRUS_HUANGLONGBING', '柑橘黄龙病', 6, 'Citrus',
     '柑橘黄龙病是毁灭性病害，由木虱传播的细菌引起。',
     '叶片黄化失绿呈斑驳状，新梢畸形，果实畸形苦味重。',
     'Bacteria', 'High', '高温干旱季节木虱多发', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CITRUS_CANKER', '柑橘溃疡病', 6, 'Citrus',
     '溃疡病为细菌性病害，危害叶、枝、果，引起疤痕。',
     '叶片、果实出现木栓化凸起斑点，周围黄晕明显。',
     'Bacteria', 'Medium', '台风暴雨、风伤多', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CITRUS_ANTHRACNOSE', '柑橘炭疽病', 6, 'Citrus',
     '炭疽病主要危害嫩梢和果实，导致枝条枯死。',
     '叶梢褐化回缩，果面出现黑色病斑并产生粉红色黏孢子。',
     'Fungus', 'Medium', '高温多雨、管理粗放', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CITRUS_RESIN_DISEASE', '柑橘树脂病', 6, 'Citrus',
     '树脂病导致树皮渗出大量树脂，严重影响生长。',
     '树干皮层裂开，渗出琥珀色树脂，枝叶黄化脱落。',
     'Bacteria', 'Medium', '连阴雨、高湿闷热', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CITRUS_GREASY_SPOT', '柑橘脂点黄斑病', 6, 'Citrus',
     '脂点黄斑病为真菌性叶斑病，叶片出现黄色油渍斑。',
     '叶面产生黄色油渍斑点，后转褐色痂斑并早期落叶。',
     'Fungus', 'Medium', '长期高湿、夜间露水', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
